spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://113.44.205.155:3306/smart-customs-platform?socketTimeout=60000&connectTimeout=30000&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: cnmngdxB999!~!
  data:
    redis:
      database: 1
      host: 113.44.205.155
      connect-timeout: 10000ms
      lettuce:
        pool:
          enabled: true
oss:
  name: minio
  bucket-name: smart-customs-platform
  endpoint: http://113.44.205.155:9010/
  access-key: XyD3l9A2Fz9TVYSKND3j
  secret-key: s2A3knISlBqZk9tGsUOmAIha3Ndc7JD7ZL3VOlGS
  sync-delete: true
  expiry: 3600

#logging:
#  level:
#    org.springframework: DEBUG