spring:
  datasource:
    url: jdbc:mysql://172.19.0.2:3306/panis_boot?socketTimeout=60000&connectTimeout=30000&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: panis
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      database: 1
      host: 172.19.0.3
      password:
      connect-timeout: 10000ms
      lettuce:
        pool:
          enabled: true
oss:
  name: minio
  bucket-name: intelligent-customs-platform
  endpoint: http://1.94.253.73:9010/
  access-key: XyD3l9A2Fz9TVYSKND3j
  secret-key: s2A3knISlBqZk9tGsUOmAIha3Ndc7JD7ZL3VOlGS
  sync-delete: true
  expiry: 3600