server:
  # 服务端口
  port: 8080

spring:
  profiles:
    # 激活环境
    active: dev
  application:
    name: smart-customs-platform
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  config:
    import:
      - classpath:config/druid.yml
      - classpath:config/mybatis-plus.yml
      - classpath:config/swagger.yml
      - classpath:config/quartz.yml